<?php

namespace AppBundle\Repository;

/**
 * ExerciseDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseDataRepository extends \Doctrine\ORM\EntityRepository
{
}
