<?php

namespace AppBundle\Repository;

/**
 * ExerciseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
