<?php

namespace AppBundle\Repository;

/**
 * ExerciceDoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceDoneRepository extends \Doctrine\ORM\EntityRepository
{
}
