<?php

namespace AppBundle\Repository;

/**
 * BadgeManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
